import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/default/Navbar";
import { AuthProvider } from "../contexts/AuthContext";
import { Inter } from 'next/font/google'

import { ToastContainer } from "react-toastify";
import Footer from "@/components/default/Footer";

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

const inter = Inter({
    subsets: ['latin']
})

export const metadata: Metadata = {
    title: "Carbon Credit Market Places",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                // className={`${geistSans.variable} ${geistMono.variable} antialiased `}
                className={`${inter.className}  `}
            >
                <AuthProvider>
                    <Navbar />
                    {children}
                    <Footer/>
                </AuthProvider>
            </body>
        </html>
    );
}
